require:
  - rubocop-performance
  - rubocop-rails

Layout/ClassStructure:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/environments/development.rb"

Metrics/MethodLength:
  Max: 15

Rails/FilePath:
  Enabled: true

Rails/Output:
  Exclude:
    - "db/seeds.rb"

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatStringToken:
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
