require:
  - rubocop-performance
  - rubocop-rails

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - "spec/spec_helper.rb"
    - "bin/**/*"
